# 服务器配置
server:
  host: "0.0.0.0"
  port: 9001
  domain: "localhost:9001"
  mode: "debug" # debug, release

# 数据库配置（支持环境变量覆盖）
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "123456"
  dbname: "gin_fata_morgana"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  conn_max_idle_time: 1800
  auto_create_index: true

# Redis配置（支持环境变量覆盖）
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3

# JWT配置
jwt:
  secret: "your-secret-key-here-change-in-production"
  access_token_expire: 86400    # 24小时
  refresh_token_expire: 604800  # 7天

# 登录缓存配置
auth:
  session_timeout: 3600
  max_login_attempts: 5
  lockout_duration: 1800

# 日志配置
log:
  level: "info"
  format: "json"
  output: "stdout"
  file:
    path: "logs/app.log"
    max_size: 100
    max_age: 30
    max_backups: 10
    compress: true

# 雪花算法配置
snowflake:
  worker_id: 1
  datacenter_id: 1

# 假订单生成配置
fake_data:
  enabled: true
  cron_expression: "0 */5 * * * *"  # 每5分钟生成订单（包含秒）
  cleanup_cron: "0 0 2 * * *"       # 每天凌晨2点清理（包含秒）
  leaderboard_cron: "0 */5 * * * *" # 每5分钟更新热榜缓存（包含秒）
  min_orders: 80
  max_orders: 100
  purchase_ratio: 0.7  # 70%购买单，30%拼单
  task_min_count: 100  # 任务数最小值
  task_max_count: 2000 # 任务数最大值
  retention_days: 2    # 保留天数 