version: '3.8'

services:
  # 主应用
  app:
    build: .
    container_name: gin-fataMorgana-app
    restart: unless-stopped
    ports:
      - "9001:9001"
    environment:
      - GIN_MODE=release
      - DATABASE_HOST=172.31.38.229
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=shgytywe!#%65926328
      - DATABASE_DBNAME=future
      - REDIS_HOST=172.31.38.229
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Test!#$1234.hjdgsag
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    networks:
      - gin-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9001/health"]
      timeout: 10s
      retries: 5

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: gin-fataMorgana-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - gin-network

networks:
  gin-network:
    driver: bridge 