services:
  # 主应用
  gin-fataMorgana:
    build: .
    image: gin-fatamorgana:latest
    container_name: gin-fataMorgana-app
    restart: unless-stopped
    ports:
      - "9001:9001"
    environment:
      - TZ=UTC
      - GIN_MODE=release
      - DATABASE_HOST=172.31.46.166
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=shgytywe!#%65926328
      - DATABASE_DBNAME=future
      - REDIS_HOST=172.31.46.166
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Test!#$1234.hjdgsag
      - SERVER_MODE=release
      - JWT_SECRET=your-super-secret-jwt-key-here
    volumes:
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - gin-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:9001/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  gin-network:
    driver: bridge
