-- 创建订单表（包含系统订单字段）
CREATE TABLE IF NOT EXISTS `orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `order_no` varchar(32) NOT NULL COMMENT '订单编号',
  `uid` varchar(8) NOT NULL COMMENT '用户唯一ID',
  `period_number` varchar(32) NOT NULL COMMENT '期号',
  `amount` decimal(15,2) NOT NULL COMMENT '订单金额',
  `profit_amount` decimal(15,2) NOT NULL COMMENT '利润金额',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '订单状态',
  `expire_time` datetime NOT NULL COMMENT '订单剩余时间',
  `like_count` int NOT NULL DEFAULT 0 COMMENT '点赞数',
  `share_count` int NOT NULL DEFAULT 0 COMMENT '转发数',
  `follow_count` int NOT NULL DEFAULT 0 COMMENT '关注数',
  `favorite_count` int NOT NULL DEFAULT 0 COMMENT '收藏数',
  `like_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '点赞完成状态',
  `share_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '转发完成状态',
  `follow_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '关注完成状态',
  `favorite_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '收藏完成状态',
  `auditor_uid` varchar(8) DEFAULT NULL COMMENT '审核员ID',
  `is_system_order` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否系统订单 0-否 1-是',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  UNIQUE KEY `uk_uid_period_number` (`uid`, `period_number`),
  KEY `idx_uid` (`uid`),
  KEY `idx_status` (`status`),
  KEY `idx_expire_time` (`expire_time`),
  KEY `idx_auditor_uid` (`auditor_uid`),
  KEY `idx_is_system_order` (`is_system_order`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_uid_status_created_at` (`uid`, `status`, `created_at`),
  KEY `idx_status_updated_at` (`status`, `updated_at`),
  KEY `idx_status_expire_time` (`status`, `expire_time`),
  KEY `idx_uid_created_at` (`uid`, `created_at`),
  KEY `idx_period_number_status` (`period_number`, `status`),
  KEY `idx_amount` (`amount`),
  KEY `idx_profit_amount` (`profit_amount`),
  KEY `idx_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表 - 记录用户订单信息，包含系统订单标识'; 