-- 创建管理员用户表
CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `admin_id` bigint unsigned NOT NULL COMMENT '管理员唯一ID',
  `username` varchar(50) NOT NULL COMMENT '用户名',
  `password` varchar(255) NOT NULL COMMENT '密码哈希',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` bigint NOT NULL DEFAULT 1 COMMENT '账户状态 1:正常 0:禁用',
  `avatar` varchar(255) DEFAULT NULL COMMENT '头像URL',
  `role` bigint NOT NULL DEFAULT 4 COMMENT '身份角色 1:超级管理员 2:经理 3:主管 4:业务员（默认业务员）',
  `my_invite_code` varchar(6) NOT NULL COMMENT '我的邀请码',
  `parent_id` bigint unsigned DEFAULT NULL COMMENT '上级用户ID',
  `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_admin_users_admin_id` (`admin_id`),
  UNIQUE KEY `idx_admin_users_username` (`username`),
  UNIQUE KEY `idx_admin_users_my_invite_code` (`my_invite_code`),
  KEY `idx_admin_users_parent_id` (`parent_id`),
  KEY `idx_admin_users_deleted_at` (`deleted_at`),
  KEY `idx_role_deleted_at` (`role`, `deleted_at`),
  KEY `idx_status_deleted_at` (`status`, `deleted_at`),
  KEY `idx_parent_id_deleted_at` (`parent_id`, `deleted_at`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='管理员用户表 - 存储管理员账户信息，支持多级角色管理，包含邀请码功能用于用户注册校验，支持软删除'; 