-- 创建拼单表
CREATE TABLE IF NOT EXISTS `group_buys` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_buy_no` varchar(32) NOT NULL COMMENT '拼单编号',
  `order_no` varchar(32) DEFAULT NULL COMMENT '关联订单编号',
  `creator_uid` varchar(8) NOT NULL COMMENT '创建用户ID',
  `uid` varchar(8) NOT NULL COMMENT '参与用户ID',
  `current_participants` int NOT NULL DEFAULT 1 COMMENT '当前参与人数',
  `target_participants` int NOT NULL DEFAULT 2 COMMENT '目标参与人数',
  `group_buy_type` varchar(20) NOT NULL DEFAULT 'normal' COMMENT '拼单类型',
  `total_amount` decimal(15,2) NOT NULL COMMENT '拼单总金额',
  `paid_amount` decimal(15,2) NOT NULL DEFAULT 0.00 COMMENT '已付款金额',
  `per_person_amount` decimal(15,2) NOT NULL COMMENT '每人需要付款金额',
  `deadline` datetime NOT NULL COMMENT '拼单截止时间',
  `status` varchar(20) NOT NULL DEFAULT 'not_started' COMMENT '拼单状态',
  `description` text COMMENT '拼单描述',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_group_buy_no` (`group_buy_no`),
  KEY `idx_order_no` (`order_no`),
  KEY `idx_creator_uid` (`creator_uid`),
  KEY `idx_uid` (`uid`),
  KEY `idx_group_buy_type` (`group_buy_type`),
  KEY `idx_deadline` (`deadline`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='拼单表 - 记录拼单信息，包括参与人数、付款金额、截止时间等';

-- 插入示例数据
INSERT INTO `group_buys` (
    `group_buy_no`, 
    `order_no`, 
    `creator_uid`, 
    `uid`, 
    `current_participants`, 
    `target_participants`, 
    `group_buy_type`, 
    `total_amount`, 
    `paid_amount`, 
    `per_person_amount`, 
    `deadline`, 
    `status`, 
    `description`
) VALUES 
(
    'GB20241201001', 
    'ORD20241201001', 
    'U001', 
    'U001', 
    1, 
    5, 
    'normal', 
    1000.00, 
    200.00, 
    200.00, 
    '2024-12-31 23:59:59', 
    'pending', 
    '限时优惠拼单，5人成团享受8折优惠'
),
(
    'GB20241201002', 
    NULL, 
    'U002', 
    'U003', 
    2, 
    3, 
    'flash', 
    600.00, 
    400.00, 
    200.00, 
    '2024-12-15 23:59:59', 
    'pending', 
    '限时闪购拼单，3人成团享受7折优惠'
),
(
    'GB20241201003', 
    NULL, 
    'U003', 
    'U003', 
    1, 
    10, 
    'vip', 
    5000.00, 
    500.00, 
    500.00, 
    '2024-12-20 23:59:59', 
    'not_started', 
    'VIP专享拼单，10人成团享受6折优惠'
); 