# 服务器配置
server:
  host: "0.0.0.0"
  port: 9001
  domain: "localhost:9001"
  mode: "debug" # debug, release

# 数据库配置
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "your_password_here"
  dbname: "gin_fata_morgana"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  # 连接池配置
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600 # 秒

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: "your_redis_password_here"
  db: 0
  # 连接池配置
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: 5 # 秒
  read_timeout: 3 # 秒
  write_timeout: 3 # 秒

# JWT配置
jwt:
  secret: "your-secret-key-change-in-production"
  access_token_expire: 3600  # 秒 (1小时)
  refresh_token_expire: 604800 # 秒 (7天)

# 登录缓存配置
auth:
  session_timeout: 3600 # 秒 (1小时)
  max_login_attempts: 5
  lockout_duration: 1800 # 秒 (30分钟)

# 日志配置
log:
  level: "info" # debug, info, warn, error
  format: "json" # json, text
  output: "stdout" # stdout, file
  file:
    path: "logs/app.log"
    max_size: 100 # MB
    max_age: 30 # 天
    max_backups: 10
    compress: true

# 雪花算法配置
snowflake:
  worker_id: 1
  datacenter_id: 1 