# 服务器配置
server:
  host: "0.0.0.0"
  port: 9001
  mode: "release"

# 数据库配置
database:
  host: "localhost"
  port: 3306
  username: "root"
  password: "root"
  dbname: "future"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # 1小时
  conn_max_idle_time: 1800 # 30分钟

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

# JWT配置
jwt:
  secret: "your-super-secret-jwt-key-here-make-it-long-and-random"
  access_token_expire: 3600    # 1小时
  refresh_token_expire: 604800 # 7天

# 雪花算法配置
snowflake:
  worker_id: 1
  datacenter_id: 1 